# Velocity Data Download Script for Validation
#### Working Script to pull large velocity datasets and later compare to ICESAT2-derived velocities

ICESat-2 hackweek  
June 15, 2020  
Lynn Kaluzienski

# Import necessary modules

In [1]:
import os
import requests
import zipfile

In [2]:
import numpy as np
import pandas as pd
import geopandas as gpd
import pyproj
import scipy, sys, os, pyproj, glob
import matplotlib.pyplot as plt
from shapely.geometry import Point, Polygon
# run matplotlib in 'widget' mode
%matplotlib widget
%load_ext autoreload
%autoreload 2

In [5]:
#! cd ..; [ -d pointCollection ] || git clone https://www.github.com/smithB/pointCollection.git
sys.path.append(os.path.join(os.getcwd(), '..'))

#!python3 -m pip install --user git+https://github.com/tsutterley/pointCollection.git@pip
import pointCollection as pc
#stuck here, not sure how to import point collection 


  Cloning https://github.com/tsutterley/pointCollection.git (to revision pip) to /tmp/pip-req-build-hm4zii0k
  Running command git clone -q https://github.com/tsutterley/pointCollection.git /tmp/pip-req-build-hm4zii0k
  Running command git checkout -b pip --track origin/pip
  Switched to a new branch 'pip'
  Branch 'pip' set up to track remote branch 'pip' from 'origin'.
  Created wheel for pointCollection: filename=pointCollection-1.0.0.0-py3-none-any.whl size=82220 sha256=d9f1e1a5eb0d00d665a441e5dfa128381c42caa5317cd9a8e24914d996c2dbe5
  Stored in directory: /tmp/pip-ephem-wheel-cache-e6x_udu6/wheels/29/6e/f2/1435b756513140ff2fc1dc41847ebca181fd3285efc91b3d86
Successfully built pointCollection


In [6]:
#Magic function to enable interactive plotting (zoom/pan) in Jupyter notebook
#If running locally, this would be `%matplotlib notebook`, but since we're using Juptyerlab, we use widget
%matplotlib widget
#%matplotlib inline

In [7]:
#Set up directories and spatial extent
data_root='/srv/shared/surface_velocity/'
#spatial_extent = np.array([-102, -76, -98, -74.5])
spatial_extent = np.array([-65, -86, -55, -81])
lat=spatial_extent[[1, 3, 3, 1, 1]]
lon=spatial_extent[[2, 2, 0, 0, 2]]
print(lat)
print(lon)
# project the coordinates to Antarctic polar stereographic
xy=np.array(pyproj.Proj(3031)(lon, lat))
# get the bounds of the projected coordinates 
XR=[np.nanmin(xy[0,:]), np.nanmax(xy[0,:])]
YR=[np.nanmin(xy[1,:]), np.nanmax(xy[1,:])]
#Load Data
Measures_vel=pc.grid.data().from_geotif(os.path.join(data_root,'FIS_Velocity','Measures2_FIS_Vel.tif'), bounds=[XR, YR])
Measures_vx=pc.grid.data().from_geotif(os.path.join(data_root,'FIS_Velocity','Measures2_FIS_Vx.tif'), bounds=[XR, YR])
Measures_vy=pc.grid.data().from_geotif(os.path.join(data_root,'FIS_Velocity','Measures2_FIS_Vy.tif'), bounds=[XR, YR])


# show the velocity map:
plt.figure()
Measures_vel.show(cmap='viridis', clim=[0, 1000])
plt.plot(xy[0,:], xy[1,:])
plt.title('Measures2 Velocity Map')


[-86 -81 -81 -86 -86]
[-55 -55 -65 -65 -55]


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

{'cmap': 'viridis', 'clim': [0, 1000], 'extent': array([-887878.65809562, -400567.81840096,  200333.90920048,
        561654.87344315]), 'origin': 'lower'}


Text(0.5, 1.0, 'Measures2 Velocity Map')

[-86 -81 -81 -86 -86]
[-55 -55 -65 -65 -55]


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

{'cmap': 'viridis', 'clim': [-500, 500], 'extent': array([-887878.65809562, -400567.81840096,  200333.90920048,
        561654.87344315]), 'origin': 'lower'}


Text(0.5, 1.0, 'Measures2 Vx component')